# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-18 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('author_name', models.CharField(max_length=15)),
                ('author_email', models.EmailField(max_length=70)),
                ('edit_date', models.DateTimeField(verbose_name='date published')),
                ('private_token', models.CharField(max_length=32)),
            ],
        ),
    ]
