# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('author_name', models.CharField(max_length=15)),
                ('author_email', models.EmailField(max_length=70)),
                ('body', models.CharField(max_length=500)),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craigslist.Announce')),
            ],
        ),
    ]
